### ISSUE TITLE
Use the SKU generator with imported products

### ISSUE THREAD

**Issue by diegozuber** [skyverge/woocommerce-product-sku-generator#15] opened 2018-11-08 11:23 UTC
I imported a set of products from an old WooCommerce Shop with an existing SKU. The ID's of these products aren't the same anymore as in the old shop. What happens if I install this Plugin and let the sku generate according the product ID? Does the plugin recognize if an sku is already in use of another product? It's importand that the old sku's remain, cause they are in use in a sync tool for the accounting software.

**Comment by bekarice** [comment] 2018-11-11 23:13
@diegozuber 👋 thanks for the Q! I'm going to close this as its a question, not a bug report / issue, but please feel free to ask questions here or [via our contact page](https://skyverge.com/contact/).

Our plugin will do nothing with imported SKUs, so you'd need to [bulk update products](https://www.skyverge.com/product/woocommerce-product-sku-generator/#bulk-update) to generate SKUs after they're imported. The plugin won't automatically look for existing SKUs, but if your products that were imported already have SKUs, WooCommerce will notify you that SKUs need to be unique, as it doesn't allow duplicates.

**Closed by bekarice** 2018-11-11 23:13 UTC
